version: '3.1'

volumes:
  pg_project:

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=viz-diz
    volumes:
      - pg_project:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"
  app:
    restart: always
    build: .
    ports:
      - "127.0.0.1:8079:8079"
    depends_on:
      - pg_db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://pg_db:5432/viz-diz'
      JAVA_OPTS: '-Xmx512m'